// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: state.sql

package db

import (
	"context"
)

const getIPv4Prefix = `-- name: GetIPv4Prefix :one
SELECT value FROM mesh_state WHERE key = 'IPv4Prefix' LIMIT 1
`

func (q *Queries) GetIPv4Prefix(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getIPv4Prefix)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getRaftState = `-- name: GetRaftState :one
SELECT 
    COALESCE((
        SELECT value FROM mesh_state WHERE key = 'CurrentRaftTerm'
    ), '') AS CurrentRaftTerm,
    COALESCE((
        SELECT value FROM mesh_state WHERE key = 'LastAppliedRaftIndex'
    ), '') AS LastAppliedRaftIndex
`

type GetRaftStateRow struct {
	CurrentRaftTerm      interface{} `json:"CurrentRaftTerm"`
	LastAppliedRaftIndex interface{} `json:"LastAppliedRaftIndex"`
}

func (q *Queries) GetRaftState(ctx context.Context) (GetRaftStateRow, error) {
	row := q.db.QueryRowContext(ctx, getRaftState)
	var i GetRaftStateRow
	err := row.Scan(&i.CurrentRaftTerm, &i.LastAppliedRaftIndex)
	return i, err
}

const getULAPrefix = `-- name: GetULAPrefix :one
SELECT value FROM mesh_state WHERE key = 'ULAPrefix' LIMIT 1
`

func (q *Queries) GetULAPrefix(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getULAPrefix)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setCurrentRaftTerm = `-- name: SetCurrentRaftTerm :exec
INSERT into mesh_state (key, value) VALUES ('CurrentRaftTerm', ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

func (q *Queries) SetCurrentRaftTerm(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, setCurrentRaftTerm, value)
	return err
}

const setIPv4Prefix = `-- name: SetIPv4Prefix :exec
INSERT into mesh_state (key, value) VALUES ('IPv4Prefix', ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

func (q *Queries) SetIPv4Prefix(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, setIPv4Prefix, value)
	return err
}

const setLastAppliedRaftIndex = `-- name: SetLastAppliedRaftIndex :exec
INSERT into mesh_state (key, value) VALUES ('LastAppliedRaftIndex', ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

func (q *Queries) SetLastAppliedRaftIndex(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, setLastAppliedRaftIndex, value)
	return err
}

const setULAPrefix = `-- name: SetULAPrefix :exec
INSERT into mesh_state (key, value) VALUES ('ULAPrefix', ?)
ON CONFLICT (key) DO UPDATE SET value = excluded.value
`

func (q *Queries) SetULAPrefix(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, setULAPrefix, value)
	return err
}
