project_name: webmesh

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: node
    main: cmd/webmesh-node/main.go
    binary: webmesh-node
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/webmesh/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/webmesh/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/webmesh/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - mips64le
      - mips64
      - mipsle
      - mips
      - riscv64

  - id: wmctl
    main: cmd/wmctl/main.go
    binary: wmctl
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/webmesh/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/webmesh/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/webmesh/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - mips64le
      - mips64
      - mipsle
      - mips
      - riscv64

  - id: turn
    main: cmd/webmesh-turn/main.go
    binary: webmesh-turn
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/webmesh/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/webmesh/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/webmesh/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - mips64le
      - mips64
      - mipsle
      - mips
      - riscv64

  - id: node-docker-linux
    main: cmd/webmesh-node/main.go
    binary: webmesh-node
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/webmesh/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/webmesh/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/webmesh/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - riscv64

  - id: turn-docker-linux
    main: cmd/webmesh-turn/main.go
    binary: webmesh-turn
    env:
      - CGO_ENABLED=0
    tags:
      - osusergo
      - netgo
    ldflags:
      - -s -w 
      - -X github.com/webmeshproj/webmesh/pkg/version.Version={{.Version}}
      - -X github.com/webmeshproj/webmesh/pkg/version.Commit={{.Commit}}
      - -X github.com/webmeshproj/webmesh/pkg/version.BuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - '386'
      - ppc64le
      - s390x
      - riscv64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

archives:
  - id: webmesh
    format: tar.gz
    builds:
      - node
      - wmctl
      - turn
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: webmesh
    maintainer: Avi Zimmerman <avi.zimmerman@gmail.com>
    description: WebMesh is a service mesh for the web
    homepage: https://webmeshproj.github.io
    license: Apache 2.0
    builds:
      - node
      - wmctl
      - turn
    formats:
      - deb
      - rpm
      - apk
      - archlinux
    recommends:
      - wireguard-tools
    archlinux:
      packager: Avi Zimmerman <avi.zimmerman@gmail.com>
      pkgbase: webmesh
    overrides:
      rpm:
        dependencies:
          - elrepo-release
          - epel-release
          - kmod-wireguard

brews:
  - ids: [webmesh]
    folder: Formula
    homepage: https://webmeshproj.github.io
    description: WebMesh is a service mesh for the web
    license: Apache 2.0
    url_template: "https://github.com/webmeshproj/webmesh/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    skip_upload: auto
    repository:
      owner: webmeshproj
      name: homebrew-repo
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: Avi Zimmerman
      email: avi.zimmerman@gmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    install: |
      bin.install "webmesh-node"
      bin.install "wmctl"
      bin.install "webmesh-turn"
      system "#{bin}/wmctl completion bash > #{bash_completion}/wmctl"
      system "#{bin}/wmctl completion zsh > #{zsh_completion}/_wmctl"
      system "#{bin}/wmctl completion fish > #{fish_completion}/wmctl.fish"
      bash_completion.install "#{bash_completion}/wmctl" => "wmctl"
    test: |
      system "#{bin}/webmesh-node --version"
      system "#{bin}/wmctl --version"

signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - "sign-blob"
      - "--yes"
      - "--oidc-issuer=https://token.actions.githubusercontent.com"
      - "--output-signature=${signature}"
      - "--output-certificate=${signature}.cert"
      - "${artifact}"
    artifacts: checksum

changelog:
  sort: asc
  filters:
    exclude:
      - '^examples:'

release:
  github:
    owner: webmeshproj
    name: webmesh
  ids:
    - webmesh
  extra_files:
    - glob: dist/*.sig
    - glob: dist/*.sig.cert

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
