FROM docker.io/library/golang:1.20-alpine AS builder

RUN apk add --no-cache git

WORKDIR /build

RUN git clone https://github.com/osrg/gobgp
WORKDIR /build/gobgp

RUN go mod download -x
RUN go build -o gobgp ./cmd/gobgp
RUN go build -o gobgpd ./cmd/gobgpd

FROM alpine:latest

COPY --from=builder /build/gobgp/gobgp /usr/local/bin/gobgp
COPY --from=builder /build/gobgp/gobgpd /usr/local/bin/gobgpd
RUN ln -s /usr/local/bin/gobgp /usr/local/bin/bgp 

ENTRYPOINT ["/usr/local/bin/gobgpd"]