// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package localdb

import (
	"context"
)

type Querier interface {
	GetCurrentRaftIndex(ctx context.Context) (RaftIndex, error)
	GetCurrentWireguardKey(ctx context.Context) (WireguardKey, error)
	SetCurrentRaftIndex(ctx context.Context, arg SetCurrentRaftIndexParams) error
	SetCurrentWireguardKey(ctx context.Context, arg SetCurrentWireguardKeyParams) error
}

var _ Querier = (*Queries)(nil)
