// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package raftdb

import (
	"database/sql"
	"time"
)

type Lease struct {
	NodeID    string    `json:"node_id"`
	Ipv4      string    `json:"ipv4"`
	CreatedAt time.Time `json:"created_at"`
}

type MeshState struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type NetworkAcl struct {
	Name       string         `json:"name"`
	SrcNodeIds sql.NullString `json:"src_node_ids"`
	DstNodeIds sql.NullString `json:"dst_node_ids"`
	SrcCidrs   sql.NullString `json:"src_cidrs"`
	DstCidrs   sql.NullString `json:"dst_cidrs"`
	Action     int64          `json:"action"`
	CreatedAt  time.Time      `json:"created_at"`
	UpdatedAt  time.Time      `json:"updated_at"`
}

type Node struct {
	ID                 string         `json:"id"`
	PublicKey          sql.NullString `json:"public_key"`
	RaftPort           int64          `json:"raft_port"`
	GrpcPort           int64          `json:"grpc_port"`
	PrimaryEndpoint    sql.NullString `json:"primary_endpoint"`
	WireguardEndpoints sql.NullString `json:"wireguard_endpoints"`
	ZoneAwarenessID    sql.NullString `json:"zone_awareness_id"`
	NetworkIpv6        sql.NullString `json:"network_ipv6"`
	CreatedAt          time.Time      `json:"created_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
}

type NodeEdge struct {
	SrcNodeID string         `json:"src_node_id"`
	DstNodeID string         `json:"dst_node_id"`
	Weight    int64          `json:"weight"`
	Attrs     sql.NullString `json:"attrs"`
}

type NodePrivateRaftAddress struct {
	NodeID  string       `json:"node_id"`
	Address sql.NullBool `json:"address"`
}

type NodePrivateRpcAddress struct {
	NodeID  string       `json:"node_id"`
	Address sql.NullBool `json:"address"`
}

type NodePublicRpcAddress struct {
	NodeID  string       `json:"node_id"`
	Address sql.NullBool `json:"address"`
}

type RaftAcl struct {
	Name      string    `json:"name"`
	Nodes     string    `json:"nodes"`
	Action    int64     `json:"action"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
