version: "3"

networks:
  public-net:
    ipam:
      driver: default
      config:
        - subnet: 10.250.0.0/24
          gateway: 10.250.0.100
  site-1:
    ipam:
      driver: default
      config:
        - subnet: 10.1.0.0/24
  site-2:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24
  site-3:
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.0/24

services:
  # Site 1

  site-1-leader:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    build:
      context: ../..
    networks:
      public-net:
        ipv4_address: 10.250.0.1
      site-1:
    hostname: site-1-leader
    entrypoint:
      - /webmesh-node
      - --global.log-level=debug
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.250.0.1
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.advertise-address=site-1-leader:9443
      - --bootstrap.servers=site-1-leader=site-1-leader:9443,site-2-leader=site-2-leader:9443,site-3-leader=site-3-leader:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --mesh.zone-awareness-id=site-1
      - --services.api.mesh
      - --services.api.admin
      - --services.meshdns.enabled
      - --services.metrics.enabled
      - --services.metrics.listen-address=:8000
      - --services.dashboard.enabled
      - --services.dashboard.listen-address=:8080
    ports:
      - 8000:8000
      - 8080:8080
      - 8443:8443
      - 5354:5353/udp
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-1-follower-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-1:
    hostname: site-1-follower-1
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-1-leader:8443
      - --mesh.max-join-retries=10
      - --mesh.zone-awareness-id=site-1
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-1-follower-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-1:
    hostname: site-1-follower-2
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-1-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-1
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-1-follower-3:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-1:
    hostname: site-1-follower-3
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-1-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-1
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  # Site 2

  site-2-leader:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.250.0.2
      site-2:
    hostname: site-2-leader
    entrypoint:
      - /webmesh-node
      - --global.log-level=debug
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.250.0.2
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.advertise-address=site-2-leader:9443
      - --bootstrap.servers=site-1-leader=site-1-leader:9443,site-2-leader=site-2-leader:9443,site-3-leader=site-3-leader:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --mesh.zone-awareness-id=site-2
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-2-follower-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-2:
    hostname: site-2-follower-1
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-2-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-2
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-2-follower-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-2:
    hostname: site-2-follower-2
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-2-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-2
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-2-follower-3:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-2:
    hostname: site-2-follower-3
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-2-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-2
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  # Site 3

  site-3-leader:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      public-net:
        ipv4_address: 10.250.0.3
      site-3:
    hostname: site-3-leader
    entrypoint:
      - /webmesh-node
      - --global.log-level=debug
      - --global.insecure
      - --global.no-ipv6
      - --global.primary-endpoint=10.250.0.3
      - --global.detect-private-endpoints
      - --bootstrap.enabled
      - --bootstrap.advertise-address=site-3-leader:9443
      - --bootstrap.servers=site-1-leader=site-1-leader:9443,site-2-leader=site-2-leader:9443,site-3-leader=site-3-leader:9443
      - --bootstrap.ipv4-network=10.10.10.0/24
      - --bootstrap.default-network-policy=accept
      - --raft.in-memory
      - --mesh.zone-awareness-id=site-3
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-3-follower-1:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-3:
    hostname: site-3-follower-1
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-3-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-3
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-3-follower-2:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-3:
    hostname: site-3-follower-2
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-3-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-3
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]

  site-3-follower-3:
    image: ${IMAGE:-ghcr.io/webmeshproj/node:latest}
    networks:
      site-3:
    hostname: site-3-follower-3
    entrypoint:
      - /webmesh-node
      - --global.insecure
      - --global.no-ipv6
      - --raft.in-memory
      - --mesh.join-address=site-3-leader:8443
      - --mesh.max-join-retries=15
      - --mesh.zone-awareness-id=site-3
    restart: on-failure
    cap_add: ["NET_ADMIN", "NET_RAW", "SYS_MODULE"]
