// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package localdb

import (
	"context"
)

type Querier interface {
	GetCurrentWireguardKey(ctx context.Context) (string, error)
	GetRaftState(ctx context.Context) (GetRaftStateRow, error)
	SetCurrentRaftTerm(ctx context.Context, value string) error
	SetCurrentWireguardKey(ctx context.Context, value string) error
	SetLastAppliedRaftIndex(ctx context.Context, value string) error
}

var _ Querier = (*Queries)(nil)
