// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package localdb

import (
	"database/sql"
)

type NodeLocalKv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type RaftIndex struct {
	ID       int64 `json:"id"`
	Term     int64 `json:"term"`
	LogIndex int64 `json:"log_index"`
}

type RaftServer struct {
	ID       string `json:"id"`
	Suffrage int64  `json:"suffrage"`
	Address  string `json:"address"`
}

type WireguardKey struct {
	ID         int64        `json:"id"`
	PrivateKey string       `json:"private_key"`
	ExpiresAt  sql.NullTime `json:"expires_at"`
}
